### ISSUE TITLE
Face_Recognition_Models packages don't match hashes from requirements file.

### ISSUE THREAD

**Issue by samhoff20** [bennuttall/piwheels#183] opened 2019-07-09 02:27 UTC
Package name: face_recognition
Issue type: Broken package (packages do not match the hashes from the requirement file)
Link to PyPI page: https://pypi.org/project/example
Link to piwheels page: https://www.piwheels.org/project/example
Version: face_recognition_models-0.3.0-py2.py3
Python version: 3.7
More information:
The hashses don't match the requirement file but everytime I try and use pip to install I get a different hash where it says "got" as opposed to "expected"
Please use code blocks where appropriate:

```bash
command line commands here
```

```python
print("code here")
```

**Comment by bennuttall** [comment] 2019-07-11 13:36
Duplicate of other issues, closing in favour of #185.

**Closed by bennuttall** 2019-07-11 13:36 UTC
