### ISSUE TITLE
Broken package: face_recognition_models

### ISSUE THREAD

**Issue by pravin-padole** [bennuttall/piwheels#184] opened 2019-07-11 12:21 UTC
Package name: example
Issue type: Installation
Link to PyPI page: https://pypi.org/project/example
Link to piwheels page: https://www.piwheels.org/project/example
Version: e.g. 1.2.3 or all
Python version: e.g. 3.5 or all
More information:

Please use code blocks where appropriate:

```HESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    scipy>=0.17.0 from https://www.piwheels.org/simple/scipy/scipy-1.3.0-cp35-cp35m-linux_armv7l.whl#sha256=fb72ea40a27497affbe729c2139e70518e992c2d6a5549052d48544b2ad8650c (from face-recognition==1.1.0):
        Expected sha256 fb72ea40a27497affbe729c2139e70518e992c2d6a5549052d48544b2ad8650c
             Got        5b2e68a30b343e356027ce2f5223d602961cda92ba8904b781b8a801245fb3fb

    face-recognition-models>=0.3.0 from https://www.piwheels.org/simple/face-recognition-models/face_recognition_models-0.3.0-py2.py3-none-any.whl#sha256=8d6b0af2e37a17120c3f13107974bc252142a4ffcb4e58eabdfcf26608e52c24 (from face-recognition==1.1.0):
        Expected sha256 8d6b0af2e37a17120c3f13107974bc252142a4ffcb4e58eabdfcf26608e52c24
             Got        0c7f263205f1513691532559c3edb7892ead68bca84351ea94cca54d4f6d88b4

```

**Comment by bennuttall** [comment] 2019-07-11 13:36
Duplicate of other issues, closing in favour of #185.

**Closed by bennuttall** 2019-07-11 13:36 UTC
