### ISSUE TITLE
Hash changed for future 0.17.1

### ISSUE THREAD

**Issue by ccatterina** [bennuttall/piwheels#164] opened 2019-06-24 08:29 UTC
Package name: future
Link to PyPI page: https://pypi.org/project/future/
Link to piwheels page: https://www.piwheels.org/simple/future/
Version: 0.17.1
Python version: all
More information:

Hi, i'm using pipenv to manage packages for my project.
Since this morning pipenv fails saying that the hashes for `future` (and also for `docopt 0.6.2`) don't match with the ones saved on Pipfile.lock (last edit 3 months ago).

```bash
['ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE.
If you have updated the package versions, please update the hashes.

Otherwise, examine the package contents carefully; someone may have tampered with them.', '    future==0.17.1 from https://www.piwheels.org/simple/future/future-0.17.1-py3-none-any.whl#sha256=dd068d8de9b395692c3d950f7a325984ebc26681bea4f46f8139eb2cabf20eff (from -r /tmp/pipenv-npi9_00u-requirements/pipenv-8qwbtmgz-requirement.txt (line 1)):', '        

Expected sha256 67045236dcfd6816dc439556d009594abf643e5eb48992e36beac09c2ca659b8', '        
Expected    or 90acf6806a8334f55d6350fff6ae63cd55eb0150960af340ee162a4c937c3b09', '            
Got        dd068d8de9b395692c3d950f7a325984ebc26681bea4f46f8139eb2cabf20eff']
```

**Comment by bennuttall** [comment] 2019-06-25 13:39
It seems to be a recurring problem with pipenv. Do any of these issues (particularly #47) help?

**Comment by ccatterina** [comment] 2019-06-26 07:18
> It seems to be a recurring problem with pipenv. Do any of these issues (particularly #47) help?

I'm probably wrong but I think that this is an unrelated issue.

In this case we have stored in the `Pipfile.lock` two hashes for both future and docopt:
```yaml
        },
        "docopt": {
            "hashes": [
                "sha256:0340515c74203895f92f87702896e45424bf51dc71bf15b4748450f50be04346",
                "sha256:49b3a825280bd66b3aa83585ef59c4a8c82f2c8a522dbe754a8bc8d08c85c491"
            ],
            "version": "==0.6.2"
        },
        "future": {
            "hashes": [
                "sha256:67045236dcfd6816dc439556d009594abf643e5eb48992e36beac09c2ca659b8",
                "sha256:90acf6806a8334f55d6350fff6ae63cd55eb0150960af340ee162a4c937c3b09"
            ],
            "version": "==0.17.1"
        },
```
Regarding docopt:

- sha `49b3a825280bd66b3aa83585ef59c4a8c82f2c8a522dbe754a8bc8d08c85c491` matches [Pypi package](https://files.pythonhosted.org/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz#sha256=49b3a825280bd66b3aa83585ef59c4a8c82f2c8a522dbe754a8bc8d08c85c491) hash
- sha `0340515c74203895f92f87702896e45424bf51dc71bf15b4748450f50be04346` **doesn't match** [piwheels package](https://www.piwheels.org/simple/docopt/docopt-0.6.2-py2.py3-none-any.whl#sha256=0553b5de94b4528793cf47ca5e47ca99067e450267209249fc593856ca0015ae) hash

Regarding future:

- sha `67045236dcfd6816dc439556d009594abf643e5eb48992e36beac09c2ca659b8` matches [Pypi package](https://files.pythonhosted.org/packages/90/52/e20466b85000a181e1e144fd8305caf2cf475e2f9674e797b222f8105f5f/future-0.17.1.tar.gz#sha256=67045236dcfd6816dc439556d009594abf643e5eb48992e36beac09c2ca659b8) hash.
- sha `90acf6806a8334f55d6350fff6ae63cd55eb0150960af340ee162a4c937c3b09` **doesn't match** [piwheels package](https://www.piwheels.org/simple/future/future-0.17.1-py3-none-any.whl#sha256=dd068d8de9b395692c3d950f7a325984ebc26681bea4f46f8139eb2cabf20eff) hash

What led me to think that hashes on piwheels are changed is that the last week we use this `Pipfile.lock` (and the same version of `pipenv`) to deploy about 20 raspberrypi without problems.

Furthermore searching for docopt hash of my `Pipfile.lock` i found the following 2 link from which i gather that `docopt 0.6.2` hash on `piwheels` was exactly the one stored in my lock file:

- https://chrxs.net/articles/2018/05/07/pip-pis-pandas-wheels/
- https://github.com/cdubz/babybuddy/issues/41

**Comment by ccatterina** [comment] 2019-06-27 07:55
I forgot to specify that we use pipenv with multiple sources:
```yaml
[[source]]

url = "https://www.piwheels.org/simple"
verify_ssl = true

[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"
```

**Comment by bennuttall** [comment] 2019-07-11 13:37
Duplicate of other issues, closing in favour of #185.

**Closed by bennuttall** 2019-07-11 13:37 UTC
Labels: question
