### ISSUE TITLE
wxPython 4 (Phoenix) Not Currently Available

### ISSUE THREAD

**Issue by GadgetSteve** [bennuttall/piwheels#99] opened 2018-10-28 12:27 UTC
Currently wxPython 4 (Phoenix) appears in the listing but the downloads page is blank for any/all of the variants. This is most likely due to missing required dependencies on Raspbian Lite on a 32 GB SD Card. 

I have successfully built & tested wxPython on a RaspberryPi 3 running a Raspbian Lite installation with the following steps:

_# Note I enabled VNC mode first which may have installed some additional dependencies not listed below._

```
sudo apt-get update
sudo apt-get install build-essential tk-dev libncurses5-dev libncursesw5-dev libreadline6-dev libdb5.3-dev libgdbm-dev libsqlite3-dev libssl-dev libbz2-dev libexpat1-dev liblzma-dev zlib1g-dev
sudo apt-get install dpkg-dev build-essential libjpeg-dev libtiff-dev libsdl1.2-dev libgstreamer-plugins-base0.10-dev libnotify-dev freeglut3 freeglut3-dev libwebkitgtk-dev
sudo apt-get install python3.5-dev
sudo apt-get install pip pip3
sudo apt-get install gtk+-3.0 gtk+3.0-dev
sudo python3 -mpip install -r requirements.txt 
sudo pip3 install wxPython
```
Once this was done I was also able to do:
```
sudo apt-get install python2.7-dev
sudo pip install -U wxPython
```
The two builds took about 7 hours in total.

_Note that while I am not a core maintainer of wxPython I am a contributor to it and can, if needed, raise tickets to request changes, etc._

**Comment by GadgetSteve** [comment] 2018-10-28 15:41
In the process of building wxPython Phoenix for Python 2.7 & 3.5 the following wheels are also generated:

 - typing-3.6.6-py2-none-any.whl
 - six-1.11.0-py2.py3-none-any.whl
 - Pypubsub-4.0.0-py3-none-any.whl
 - Pypubsub-4.0.0-py2-none-any.whl

Since these, (with the possible exception of Ppubsub-4.0.0-py2), are already available from piwheels it would be a time saver to `sudo pip install` them all first.

**Comment by bennuttall** [comment] 2018-10-28 20:02
Duplicate of #54 - please add extra information there (and in future please use our issue templates). Don't worry about user requirements, all wheels are build singularly.

Note that we don't currently build for Python 2, so if you can help us build it for Python 3, please use #54.

**Closed by bennuttall** 2018-10-28 20:02 UTC
