### ISSUE TITLE
Packages with `.` in their names are searched with `-`.

### ISSUE THREAD

**Issue by mishas** [bennuttall/piwheels#20] opened 2017-08-31 09:14 UTC
Running `pip3 -v install rpi.gpio` searches the `https://pypi.python.org/simple/rpi-gpio/` url (and subsequently the `https://www.piwheels.hostedpi.com/simple/rpi-gpio/` url when this awesome project is used).

Looking at your index, rpi.gpio IS indexed, but it resides in `https://www.piwheels.hostedpi.com/simple/rpi.gpio/` (with `.` instead of `-`).

The problem is magnified by this bug [here](https://github.com/pypa/pip/issues/4580), that makes pip sometimes fail completely if it's not in the provided index :(.

**Comment by waveform80** [comment] 2017-08-31 13:57
Damn - I'll get that fixed up once I've found out exactly where pip is sanitizing names (so I can copy their algorithm)

**Comment by mishas** [comment] 2017-08-31 15:33
Here's the code in pip: https://github.com/pypa/pip/blob/master/pip/_vendor/packaging/utils.py

You can see that this file has only one method: `canonicalize_name` which is what you're looking for.

**Comment by mishas** [comment] 2017-08-31 15:35
This function apparently comes from `pip install packaging` and then `import packaging.utils; packaging.utils.canonicalize_name(name)`

**Comment by waveform80** [comment] 2017-08-31 15:36
Lovely stuff - that'll save me a bit of time later, thanks!

**Comment by dnviti** [comment] 2017-10-01 10:24
is this issue going to be fixed?

**Comment by nachoparker** [comment] 2017-10-01 11:18
please, prioritize this. It is preventing letsencrypt to work on Raspbian.

**Comment by maxverstappen** [comment] 2017-10-01 11:29
+1

**Comment by isaachoo** [comment] 2017-10-01 14:45
+1 more here

**Comment by traily** [comment] 2017-10-01 15:13
is there any workaround in the meantime?

**Comment by ShashankJain123** [comment] 2017-10-01 17:20
Solution for lets encrypt on Raspberry PI only (atleast what I know of)

I managed to solve this by giving the auto script an additional repository to look for files; in this case **zope.component** rather than **zope-component**

To do this modify /etc/pip.conf and add the below line item
extra-index-url=https://www.piwheels.hostedpi.com/simple/zope.components

Worked like charm and certificate has been generated.

PS: I am not a programmer or a coder and don't know anything about pip or python. This may be a temporary solution and worked for me; so should for you.

**Comment by waveform80** [comment] 2017-10-27 22:05
This *should* be fixed in the new version I'm deploying into production:

1. I've constructed symlinks from "canonicalized" names to "actual" names in the package directory served up by Apache
2. The new system should construct canonicalized symlinks for all new packages as they're added
3. The new version now in production supports multiple ABIs so it's currently ploughing through building stuff for the 3.5 ABI wih a few build-slaves running stretch (~13k packages). This'll take a while so don't be surprised if stuff doesn't work for 3.5 yet.

Why symlinks? Why not rename the existing directories? It turns out that's not enough: sometimes pip wants the actual package name (note that the PyPI simple index entry for RPi.GPIO is still RPi.GPIO not rpi-gpio, although trying rpi-gpio redirects to the "actual" name). So, we need both. Simplest way to do this without wasting too much space is symlinks. Then there's the issue with packages that map to the same canonicalized name (I think this is a historical artifact and shouldn't happen anymore, but they're still listed in the XML and JSON output by PyPI so there's some workarounds in the code for them).

Anyway, I'll leave this open for now until we've got a fair selection of 3.5 packages to test with as well, but feel free to try it with 3.4 stuff.

**Comment by nachoparker** [comment] 2017-10-29 14:10
Thank you, I can confirm that letsencrypt build for NextCloudPi now works without workarounds

**Comment by waveform80** [comment] 2017-10-29 21:10
@nachoparker Excellent, thanks for the confirmation.

I've tested this with RPi.GPIO on 3.4 and 3.5 which both work nicely so I'm reasonably confident this is fixed. I'll close the ticket at this point, but if anyone comes across this particular issue again do feel free to comment here and I'll look into it.

**Closed by waveform80** 2017-10-29 21:10 UTC
Labels: bug
