### ISSUE TITLE
hash sum mismatch for tensorflow

### ISSUE THREAD

**Issue by jainthedestroyer** [bennuttall/piwheels#170] opened 2019-06-27 22:00 UTC
Package name: tensorflow
Link to PyPI page: https://pypi.org/project/tensorflow
Link to piwheels page: https://www.piwheels.org/project/tensorflow
Version: 1.13.1
Python version: 3.7.3
More information:

```
pi@raspberrypi:~ $ pip3 install tensorflow
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting tensorflow
  Downloading https://www.piwheels.org/simple/tensorflow/tensorflow-1.13.1-cp37-none-linux_armv7l.whl (93.2MB)
     |█▍                              | 3.9MB 512kB/s eta 0:02:55
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    tensorflow from https://www.piwheels.org/simple/tensorflow/tensorflow-1.13.1-cp37-none-linux_armv7l.whl#sha256=25f4ff027beec1e568baf8e90a07bad59d354560533d6b37318b9efeb70beeb1:
        Expected sha256 25f4ff027beec1e568baf8e90a07bad59d354560533d6b37318b9efeb70beeb1
             Got        1e0ae90c25470daff7f56e5975a44411fed8d3549f2a4cf725ef39051eca9d50
```

**Comment by bennuttall** [comment] 2019-06-28 10:33
This was reported in #146 - not sure what's causing it.

You can download the wheel and install it in two steps:

```
wget https://www.piwheels.org/simple/tensorflow/tensorflow-1.13.1-cp37-none-linux_armv7l.whl
sudo pip3 install tensorflow*.whl
```

**Comment by bennuttall** [comment] 2019-06-28 10:34
Also, FYI, it wasn't helpful that you didn't fill out the issue template. I've done it for you.

**Comment by jainthedestroyer** [comment] 2019-06-28 10:57
When I use the command suggested above it shows that the file is not supported on this platform...

**Comment by bennuttall** [comment] 2019-06-28 10:58
What OS version, Python version and Pi model?

**Comment by jainthedestroyer** [comment] 2019-06-28 17:15
OS =  
Raspbian Buster with desktop
Version: June 2019
Release date: 2019-06-20
Kernel version: 4.19

python version= 3.7.3

pi model = 3B+

**Comment by OnlinePseudonym** [comment] 2019-06-30 19:55
I was running into the same issue attempting to run `pip3 install tensorflow` on a Raspberry Pi 4 running Raspbian Buster on Python 3.7.3

When I split up the download and install I was getting this read error every few mbs but it eventually completed after 14 tries.
```
2019-06-30 12:17:46 (131 KB/s) - Read error at byte 3620864/93225710 (Error decoding the received TLS packet.). Retrying.
```

After attempting to install the wheel I I got similar hash errors for a couple of dependencies

```
THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    grpcio>=1.8.6 from https://www.piwheels.org/simple/grpcio/grpcio-1.21.1-cp37-cp37m-linux_armv7l.whl#sha256=676495c9942aa7fcd69f9226d062fe124e232efd815e052d705c7b37575c853f (from tensorflow==1.13.1):
        Expected sha256 676495c9942aa7fcd69f9226d062fe124e232efd815e052d705c7b37575c853f
             Got        1493a6cb26b6a21e4920da3f677e43ccfb98d7c169c0ccea3e2de5cba5fe0404

    h5py from https://www.piwheels.org/simple/h5py/h5py-2.9.0-cp37-cp37m-linux_armv7l.whl#sha256=a7a760e2e05e914da993f96f4d0d8d7490aa1200d96a80ec4cc07fee736c8b58 (from keras-applications>=1.0.8->tensorflow==1.13.1):
        Expected sha256 a7a760e2e05e914da993f96f4d0d8d7490aa1200d96a80ec4cc07fee736c8b58
             Got        f424d8fb2aaacc1eef2d25fec6786713e56971138f729dd8363c1f1212149a69
```

After I downloaded the grpcio and h5py wheels and installing them I was able to install the tensorflow wheel. Not sure what exactly that all means but I thought it might help here.

**Comment by bennuttall** [comment] 2019-07-11 13:36
Duplicate of other issues, closing in favour of #185.

**Closed by bennuttall** 2019-07-11 13:36 UTC
Labels: broken package
