### ISSUE TITLE
Different hashes for pycparser

### ISSUE THREAD

**Issue by Iraklis** [bennuttall/piwheels#144] opened 2019-04-09 00:34 UTC
Broken package
Package name: pycparser
Link to piwheels page: https://www.piwheels.org/project/pycparser/
Version: 2.19
Python version: 3.5

Although I could install fine pycparser with both `pip3 install pycparser ` and `pip install pycparser `, upon updating my certificates with certbot I ran into this: 

```bash
sudo ./certbot-auto renew
Bootstrapping dependencies for Debian-based OSes... (you can skip this with --no-bootstrap)

[ommiting]

Creating virtual environment...
Installing Python packages...

[ommiting]

THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    pycparser==2.19 from https://www.piwheels.org/simple/pycparser/pycparser-2.19-py2.py3-none-any.whl#sha256=344870c533812cb119c5475b5aed033ec546118711338ff9b2b78e67098d64e7 (from -r /tmp/tmp.Ndt9uTrO2k/letsencrypt-auto-requirements.txt (line 105)):
        Expected sha256 a988718abfad80b6b157acce7bf130a30876d27603738ac39f140993246b25b3
             Got        344870c533812cb119c5475b5aed033ec546118711338ff9b2b78e67098d64e7

```
After a bit of fiddling around I realised that certbot tries to download pycparser from piwheels, (sha: `344870c533812cb119c5475b5aed033ec546118711338ff9b2b78e67098d64e7`), but it somehow gets the sha checksum from [pypi](https://pypi.org/project/pycparser/), which is: `a988718abfad80b6b157acce7bf130a30876d27603738ac39f140993246b25b3`.
I am not that into installing python packages, so this is the most that I can get from it. Any suggestions would be nice. Oh, the platform is a raspberrypi 2 by the way. 

Thanks in advance.

**Comment by bennuttall** [comment] 2019-04-09 09:14
It doesn't sound like this is an issue with piwheels. As you said, the hashes match but it's comparing pypi's hash to the piwheels one.

I have seen this before when someone was using pipenv, which has a lock file containing the hashes of packages, and that would fail checks when you changed system. See #47.

It looks like certbot is doing something similar. You can see [here](https://github.com/certbot/certbot/blob/master/letsencrypt-auto-source/pieces/dependency-requirements.txt#L105) that they specify hashes for each dependency. I can't imagine what the benefit of this could be, but it will certainly break for piwheels.

Maybe if you install all the dependencies yourself (every package listed in the requirements file linked above), then try to run certbot, it shouldn't need to install anything.

**Comment by Iraklis** [comment] 2019-04-09 09:42
You are right, the problem was a 'misconfiguration' from my part (kinda), but I was brain dead at the time and I couldn't find the problem. For what it's worth, I finally found what the problem was, `/etc/pip.conf` had an entry that pointed to piwheels for some reason than pypi, so that created the conflict. All I did was to delete (or better rename the file) and everything went smooth after that. Thanks!

**Comment by bennuttall** [comment] 2019-04-09 10:01
`pip.conf` is supposed to be there. I'd suggest you reinstate it after you're done with certbot.

certbot seems to currently require you to only use PyPI because it insists on particular hashes. But normally, when you install from with `pip` you want to get files from piwheels.org as they're pre-compiled so they're much faster to install. That's why this project exists.

I've filed an issue with certbot to discuss options: https://github.com/certbot/certbot/issues/6933

**Comment by bennuttall** [comment] 2019-07-11 13:37
Duplicate of other issues, closing in favour of #185.

**Closed by bennuttall** 2019-07-11 13:37 UTC
Labels: upstream-issue
