### ISSUE TITLE
www.piwheels.org 503 Error

### ISSUE THREAD

**Issue by scisslehannd** [bennuttall/piwheels#64] opened 2018-04-17 20:33 UTC
Hello, I'm trying to use pip and it seems that the website www.piwheels.org is down. Returning a 503 error on my mac. Any way we can help resolve this issue? Is there a way I can bypass using www.piwheels.org when using pip on the rpi? 

Thanks,

**Comment by bennuttall** [comment] 2018-04-19 10:12
Duplicate of #62 - see my response there.

**Closed by bennuttall** 2018-04-19 10:12 UTC
